version: '3'

networks:
  onlyoffice:

volumes:
  postgresql:

services:
  onlyoffice:
    image: knoxzhang/oo-ce-docker-license:7.1.1.23-arm64
    container_name: onlyoffice
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-redis
      - onlyoffice-rabbitmq
    env_file: config.env
    ports:
      - 91:80
    restart: always
    networks:
       - onlyoffice
       
  onlyoffice-redis:
    container_name: onlyoffice-redis
    image: redis
    restart: always
    expose:
      - '6379'
    networks:
       - onlyoffice

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'
    networks:
       - onlyoffice

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    volumes: 
      - ./postgresql:/var/lib/postgresql/data/
    expose:
      - '5432'
    networks:
      - onlyoffice
