version: '3'
services:
  onlyoffice:
    image: knoxzhang/oo-ce-docker-license:7.1.1.23-arm64
    container_name: onlyoffice
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-redis
      - onlyoffice-rabbitmq
    env_file: config.env
    ports:
        - 91:80
#        - 91:443
    restart: always
    volumes:
       - ./nginx:/etc/nginx/conf.d
       - /var/www/onlyoffice/Data
       - /var/log/onlyoffice
       - /var/lib/onlyoffice/documentserver/App_Data/cache/files
       - /var/www/onlyoffice/documentserver-example/public/files
       - .fonts:/usr/share/fonts

  onlyoffice-redis:
    container_name: onlyoffice-redis
    image: redis
    restart: always
    expose:
      - '6379'

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'

volumes:
  postgresql_data:
  nginx:
  fonts:
